"""empty message

Revision ID: 912ba3bc8017
Revises: 
Create Date: 2022-04-13 17:41:43.225334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912ba3bc8017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_comm_all',
    sa.Column('comm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comm_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('comm_id')
    )
    op.create_table('mc_user_all',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('mcs_comm',
    sa.Column('comm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_num', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('sale_amt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('comm_id')
    )
    op.create_table('order_sale',
    sa.Column('sale_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_num', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('ticket', sa.String(length=20), nullable=True),
    sa.Column('sale_num', sa.String(length=20), nullable=True),
    sa.Column('sale_line_num', sa.String(length=5), nullable=True),
    sa.Column('item_no', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('amt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sale_line_id')
    )
    op.create_table('broker',
    sa.Column('broker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('broker_num', sa.String(length=10), nullable=False),
    sa.Column('travel', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('broker_id')
    )
    op.create_table('comm',
    sa.Column('comm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_num', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('sale_amt', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('comm_amt', sa.Integer(), nullable=False),
    sa.Column('comm_type', sa.String(length=30), nullable=False),
    sa.Column('cal_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('comm_id')
    )
    op.create_table('mc_id_set_all',
    sa.Column('id_no', sa.String(length=12), nullable=False),
    sa.Column('id_num', sa.String(length=10), nullable=False),
    sa.Column('id_name', sa.String(length=50), nullable=False),
    sa.Column('phone_num', sa.String(length=10), nullable=False),
    sa.Column('id_type', sa.String(length=1), nullable=False),
    sa.Column('id_value_code', sa.String(length=10), nullable=False),
    sa.Column('id_value_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('id_mark', sa.String(length=10), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('creation_by', sa.String(length=10), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['creation_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('id_no'),
    sa.UniqueConstraint('id_num')
    )
    op.create_table('mc_register_all',
    sa.Column('register_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uniform_num', sa.String(length=8), nullable=False),
    sa.Column('site_name', sa.String(length=30), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('creation_by', sa.String(length=10), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['creation_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('register_id'),
    sa.UniqueConstraint('uniform_num')
    )
    op.create_table('mc_value_set_all',
    sa.Column('set_value_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_type', sa.String(length=30), nullable=False),
    sa.Column('value_code', sa.String(length=10), nullable=True),
    sa.Column('value_name', sa.String(length=100), nullable=False),
    sa.Column('value_desc', sa.String(length=200), nullable=True),
    sa.Column('parent_value', sa.String(length=10), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('creation_by', sa.String(length=10), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['creation_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('set_value_id')
    )
    op.create_table('mcs_comm_line',
    sa.Column('comm_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('sale_line_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=20), nullable=False),
    sa.Column('sale_num', sa.String(length=20), nullable=False),
    sa.Column('sale_line_num', sa.String(length=5), nullable=False),
    sa.Column('item_no', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['mcs_comm.comm_id'], ),
    sa.PrimaryKeyConstraint('comm_line_id')
    )
    op.create_table('comm_broker',
    sa.Column('comm_broker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.broker_id'], ),
    sa.ForeignKeyConstraint(['comm_id'], ['comm.comm_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('comm_broker_id')
    )
    op.create_table('comm_line',
    sa.Column('comm_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('sale_line_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=20), nullable=False),
    sa.Column('sale_num', sa.String(length=20), nullable=False),
    sa.Column('sale_line_num', sa.String(length=5), nullable=False),
    sa.Column('item_no', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['comm.comm_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('comm_line_id')
    )
    op.create_table('mc_income_all',
    sa.Column('form_id', sa.String(length=7), nullable=False),
    sa.Column('uniform_num', sa.String(length=8), nullable=False),
    sa.Column('id_no', sa.String(length=12), nullable=False),
    sa.Column('id_num', sa.String(length=10), nullable=False),
    sa.Column('id_name', sa.String(length=50), nullable=False),
    sa.Column('income_yyy', sa.String(length=3), nullable=False),
    sa.Column('income_mm', sa.String(length=2), nullable=False),
    sa.Column('income_format', sa.String(length=10), nullable=False),
    sa.Column('income_mark', sa.String(length=10), nullable=True),
    sa.Column('income_amt', sa.Integer(), nullable=False),
    sa.Column('tax_amt', sa.Integer(), nullable=False),
    sa.Column('net_amt', sa.Integer(), nullable=False),
    sa.Column('exe_industry', sa.String(length=10), nullable=True),
    sa.Column('other_income', sa.String(length=10), nullable=True),
    sa.Column('royalties_exp', sa.String(length=10), nullable=True),
    sa.Column('house_tax_num', sa.String(length=20), nullable=True),
    sa.Column('house_address', sa.String(length=200), nullable=True),
    sa.Column('declare_status', sa.BOOLEAN(), nullable=False),
    sa.Column('comm_flag', sa.BOOLEAN(), nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('creation_by', sa.String(length=10), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['mc_comm_all.comm_id'], ),
    sa.ForeignKeyConstraint(['creation_by'], ['mc_user_all.account'], ),
    sa.ForeignKeyConstraint(['id_no'], ['mc_id_set_all.id_no'], ),
    sa.ForeignKeyConstraint(['id_num'], ['mc_id_set_all.id_num'], ),
    sa.ForeignKeyConstraint(['uniform_num'], ['mc_register_all.uniform_num'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['mc_user_all.account'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mc_income_all')
    op.drop_table('comm_line')
    op.drop_table('comm_broker')
    op.drop_table('mcs_comm_line')
    op.drop_table('mc_value_set_all')
    op.drop_table('mc_register_all')
    op.drop_table('mc_id_set_all')
    op.drop_table('comm')
    op.drop_table('broker')
    op.drop_table('order_sale')
    op.drop_table('mcs_comm')
    op.drop_table('mc_user_all')
    op.drop_table('mc_comm_all')
    # ### end Alembic commands ###
