"""empty message

Revision ID: d0140bb1fd92
Revises: 
Create Date: 2022-04-15 09:07:05.750721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0140bb1fd92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanban_comm',
    sa.Column('comm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_num', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('sale_amt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('comm_id')
    )
    op.create_table('order_sale',
    sa.Column('sale_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_num', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('ticket', sa.String(length=20), nullable=True),
    sa.Column('sale_num', sa.String(length=20), nullable=True),
    sa.Column('sale_line_num', sa.String(length=5), nullable=True),
    sa.Column('item_no', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('amt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sale_line_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('broker',
    sa.Column('broker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('broker_num', sa.String(length=10), nullable=False),
    sa.Column('travel', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('broker_id')
    )
    op.create_table('comm',
    sa.Column('comm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_num', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('sale_amt', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('comm_amt', sa.Integer(), nullable=False),
    sa.Column('comm_type', sa.String(length=30), nullable=False),
    sa.Column('cal_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('comm_id')
    )
    op.create_table('id_set',
    sa.Column('id_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_no', sa.String(length=12), nullable=False),
    sa.Column('id_num', sa.String(length=10), nullable=False),
    sa.Column('id_name', sa.String(length=50), nullable=False),
    sa.Column('phone_num', sa.String(length=10), nullable=False),
    sa.Column('id_type', sa.String(length=1), nullable=False),
    sa.Column('id_value_code', sa.String(length=10), nullable=False),
    sa.Column('id_value_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('id_mark', sa.String(length=10), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('id_id'),
    sa.UniqueConstraint('id_no'),
    sa.UniqueConstraint('id_num')
    )
    op.create_table('kanban_comm_line',
    sa.Column('comm_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('sale_line_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=20), nullable=False),
    sa.Column('sale_num', sa.String(length=20), nullable=False),
    sa.Column('sale_line_num', sa.String(length=5), nullable=False),
    sa.Column('item_no', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['kanban_comm.comm_id'], ),
    sa.PrimaryKeyConstraint('comm_line_id')
    )
    op.create_table('register',
    sa.Column('register_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uniform_num', sa.String(length=8), nullable=False),
    sa.Column('site_name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('register_id'),
    sa.UniqueConstraint('uniform_num')
    )
    op.create_table('value_set',
    sa.Column('set_value_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_type', sa.String(length=30), nullable=False),
    sa.Column('value_code', sa.String(length=10), nullable=True),
    sa.Column('value_name', sa.String(length=100), nullable=False),
    sa.Column('value_desc', sa.String(length=200), nullable=False),
    sa.Column('parent_value', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('set_value_id')
    )
    op.create_table('comm_broker',
    sa.Column('comm_broker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.broker_id'], ),
    sa.ForeignKeyConstraint(['comm_id'], ['comm.comm_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('comm_broker_id')
    )
    op.create_table('comm_line',
    sa.Column('comm_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('sale_line_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=20), nullable=False),
    sa.Column('sale_num', sa.String(length=20), nullable=False),
    sa.Column('sale_line_num', sa.String(length=5), nullable=False),
    sa.Column('item_no', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['comm.comm_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('comm_line_id')
    )
    op.create_table('pay',
    sa.Column('pay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_date', sa.DateTime(), nullable=False),
    sa.Column('decl_type', sa.String(length=20), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=10), nullable=True),
    sa.Column('uniform_num', sa.String(length=8), nullable=True),
    sa.Column('site_name', sa.String(length=50), nullable=True),
    sa.Column('pay_status', sa.String(length=20), nullable=False),
    sa.Column('decl_status', sa.String(length=1), nullable=False),
    sa.Column('total_amt', sa.Integer(), nullable=False),
    sa.Column('tax_amt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.broker_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    op.create_table('income',
    sa.Column('form_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_no', sa.String(length=7), nullable=False),
    sa.Column('uniform_num', sa.String(length=8), nullable=False),
    sa.Column('id_no', sa.String(length=12), nullable=False),
    sa.Column('id_num', sa.String(length=10), nullable=False),
    sa.Column('id_name', sa.String(length=50), nullable=False),
    sa.Column('yyy', sa.String(length=3), nullable=False),
    sa.Column('mm', sa.String(length=2), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('mark', sa.String(length=10), nullable=True),
    sa.Column('amt', sa.Integer(), nullable=False),
    sa.Column('tax_amt', sa.Integer(), nullable=False),
    sa.Column('net_amt', sa.Integer(), nullable=False),
    sa.Column('exe_industry', sa.String(length=10), nullable=True),
    sa.Column('other_income', sa.String(length=10), nullable=True),
    sa.Column('roya_exp', sa.String(length=10), nullable=True),
    sa.Column('house_tax', sa.String(length=20), nullable=True),
    sa.Column('house_add', sa.String(length=200), nullable=True),
    sa.Column('decl_status', sa.String(length=1), nullable=False),
    sa.Column('pay_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['id_no'], ['id_set.id_no'], ),
    sa.ForeignKeyConstraint(['id_num'], ['id_set.id_num'], ),
    sa.ForeignKeyConstraint(['pay_id'], ['pay.pay_id'], ),
    sa.ForeignKeyConstraint(['uniform_num'], ['register.uniform_num'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('form_id'),
    sa.UniqueConstraint('form_no')
    )
    op.create_table('pay_line',
    sa.Column('pay_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('comm_broker_id', sa.Integer(), nullable=True),
    sa.Column('pay_type', sa.String(length=20), nullable=False),
    sa.Column('pay_amt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['comm_broker_id'], ['comm_broker.comm_broker_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.account'], ),
    sa.ForeignKeyConstraint(['pay_id'], ['pay.pay_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.account'], ),
    sa.PrimaryKeyConstraint('pay_line_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pay_line')
    op.drop_table('income')
    op.drop_table('pay')
    op.drop_table('comm_line')
    op.drop_table('comm_broker')
    op.drop_table('value_set')
    op.drop_table('register')
    op.drop_table('kanban_comm_line')
    op.drop_table('id_set')
    op.drop_table('comm')
    op.drop_table('broker')
    op.drop_table('user')
    op.drop_table('order_sale')
    op.drop_table('kanban_comm')
    # ### end Alembic commands ###
